#############################################################################
# Makefile for building: securesocketclient
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Aug 22 09:45:46 2024
# Project:  securesocketclient.pro
# Template: app
# Command: /usr/local/qt/bin/qmake -o Makefile securesocketclient.pro
#############################################################################

QMAKE    = /usr/local/qt/bin/qmake
check mocclean mocables first all clean install distclean uninstall qmake_all:
	@echo "Some of the required modules (qtHaveModule(network) qtConfig(listwidget) qtConfig(combobox)) are not available."
	@echo "Skipped."

Makefile: securesocketclient.pro  /usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/../common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/../common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/../common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile securesocketclient.pro
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/../common/linux.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/../common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/../common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/shared.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile securesocketclient.pro

FORCE:

